from typing import Protocol, runtime_checkable


@runtime_checkable
class ICombatant(Protocol):
    """Combat participant — attack and receive damage."""
    @property
    def name(self) -> str: ...
    def attack(self) -> int: ...
    def defense(self, damage: int) -> dict: ...


@runtime_checkable
class IIdentifiable(Protocol):
    """Monster with hidden identity revealed through clues. ISP: separate from combat."""
    def next_action(self) -> str: ...
    def get_clue(self, round_num: int) -> str | None: ...
    def get_geralt_thought(self, round_num: int, identified: bool) -> str | None: ...
    def hp_status(self) -> str: ...
